version: '3'
services:
  web:
    image: localhost:5000/flask:latest
    build: .
    ports:
      - "5001:5000"
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 250M
        reservations:
          cpus: '1.0'
          memory: 200M