version: "3.7"
services:
  my-node:
    image: nginx
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 50M
        reservations:
          cpus: '1.0'
          memory: 20M
